########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    - sr/es-alias # Sravan Nov 18
    - ce/bulk-case-search # Cal July 6
    #- sr/memoized-toggle # Sravan July 26
    - smh/remove-extra-spinner-icons # Steph Oct 6
    - ml/remove-pickles-phonelog # Minha Oct 7
    - dependabot/npm_and_yarn/moment-2.29.1 # Amit Oct 8
    # - dependabot/pip/requirements/certifi-2021.10.8   # SK / Joel Oct 12
    - es/mobile-auth # Simon Nov 23
    - dm/django3-branches+others
    - ml/remove-pickles-reports # Minha Jan 24
    - do/compare-case-properties # Dominic Feb 2
    # - mk/support-expanded-cols-in-mobile-ucr # MK Feb 2
    - gh/mrm/base # Graham Feb 8
    - gh/form-version-bug # Graham Feb 15
    - gh/erm/consolidate-enterprise-roles # Graham Feb 20
    - bmb/whh-003 # Biyeun Mar 1
    - nh/loadtest_users_ga+others  # Norman Mar 2
    # - ad/multivalued-search-functions # Addison Mar 2
    - ml/check-for-historical-xss # Minha Mar 3
    - ad/DSF-curly-braces-interpolation-syntax # Addison Mar 7
    - dm/django3.0-part1 # Daniel 3/9
    - jm/elastic-client-adapter  # Joel Mar 1
    - ml/sumologic-on-staging-check # Minha Mar 10
    - dm/django3.1-deprecations # Daniel 3/14
submodules: { }
