name: type-checking

on:
  push:
    paths:
      - '**.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy @mypy_typed_modules.txt
